# See https://github.com/cypress-io/circleci-orb
version: 2.1
orbs:
  continuation: circleci/continuation@0.1.2
workflows:
  build:
    jobs:
      - cypress/run

      # another independent job
      # testing how the orb can install and build
      # in the subfolder
      - cypress/install:
          name: subfolder install and build
          working_directory: examples/subfolder
          build: npm run build
